PCMO - DEPO SEMARANG	=	GENUK B
PCMO - SEMARANG = GENUK B
PCMO - JOGJA	=	JOGJA
PCMO - DEPO SEMARANG	=	MATARAM
PCMO - MAGELANG	=	MGL
PCMO - PATI KUDUS	=	PATI KUDUS
PCMO - PURWOKERTO	=	PURWOKERTO
PCMO - SOLO	=	SOLO
PCMO - TEGAL 	=	TEGAL
MCO - KENDARI	=	KENDARI
MCO - MAKASAR	=	MAKASAR
MCO - PALU	=	PALU
PCMO - KENDARI	=	KENDARI
PCMO - MAKASAR	=	MAKASAR
PCMO - PALU	=	PALU
